/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Dec 27 09:10:07 GMT 2019
 */

package org.sse.recommendservice.controller;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class RecommendController_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.sse.recommendservice.controller.RecommendController"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/d3/k2gc1l3d2v56t6f1l9xsh6jm0000gn/T/"); 
    java.lang.System.setProperty("user.country", "CN"); 
    java.lang.System.setProperty("user.dir", "/Users/cbc/Project/Java/ChiSha/recommend-service"); 
    java.lang.System.setProperty("user.home", "/Users/cbc"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "cbc"); 
    java.lang.System.setProperty("user.timezone", "Asia/Shanghai"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(RecommendController_ESTest_scaffolding.class.getClassLoader() ,
      "org.supercsv.io.ICsvWriter",
      "org.springframework.util.LinkedCaseInsensitiveMap$EntrySetIterator",
      "org.sse.recommendservice.service.RecommendService",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.http.MediaType$1",
      "org.springframework.beans.factory.annotation.Autowired",
      "org.supercsv.io.ICsvListWriter",
      "org.springframework.stereotype.Controller",
      "org.springframework.http.ResponseEntity$BodyBuilder",
      "org.springframework.http.ReadOnlyHttpHeaders",
      "org.sse.recommendservice.controller.RecommendController",
      "org.springframework.core.io.WritableResource",
      "org.springframework.util.LinkedCaseInsensitiveMap$EntrySet",
      "org.springframework.util.MimeType",
      "org.springframework.stereotype.Service",
      "org.springframework.util.MimeType$SpecificityComparator",
      "org.springframework.stereotype.Indexed",
      "org.springframework.core.io.Resource",
      "org.springframework.util.InvalidMimeTypeException",
      "org.springframework.util.MimeTypeUtils$ConcurrentLruCache",
      "org.springframework.util.LinkedCaseInsensitiveMap$EntryIterator",
      "org.springframework.http.HttpHeaders",
      "org.springframework.http.ResponseEntity$DefaultBuilder",
      "org.springframework.http.MediaType",
      "org.springframework.util.ObjectUtils",
      "org.springframework.core.io.FileSystemResource",
      "org.springframework.util.MultiValueMap",
      "org.springframework.core.NestedIOException",
      "org.springframework.util.MimeTypeUtils",
      "org.springframework.web.bind.annotation.ResponseBody",
      "org.springframework.web.bind.annotation.RestController",
      "org.springframework.core.io.AbstractResource",
      "org.springframework.util.CollectionUtils$MultiValueMapAdapter",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.http.HttpStatus",
      "org.springframework.http.InvalidMediaTypeException",
      "org.springframework.http.HttpEntity",
      "org.springframework.stereotype.Component",
      "org.springframework.util.CollectionUtils",
      "org.springframework.core.io.InputStreamSource",
      "org.springframework.http.ResponseEntity",
      "org.springframework.http.ResponseEntity$HeadersBuilder",
      "org.springframework.util.LinkedMultiValueMap",
      "org.springframework.util.Assert",
      "org.springframework.util.StringUtils"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.sse.recommendservice.service.RecommendService", false, RecommendController_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(RecommendController_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.sse.recommendservice.controller.RecommendController",
      "org.springframework.http.HttpStatus",
      "org.springframework.util.MimeType$SpecificityComparator",
      "org.springframework.util.MimeTypeUtils$ConcurrentLruCache",
      "org.springframework.util.Assert",
      "org.springframework.util.MimeType",
      "org.springframework.util.StringUtils",
      "org.springframework.util.CollectionUtils",
      "org.springframework.util.MimeTypeUtils",
      "org.sse.recommendservice.service.RecommendService",
      "org.springframework.http.ReadOnlyHttpHeaders",
      "org.springframework.util.LinkedMultiValueMap",
      "org.springframework.http.HttpHeaders",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.util.CollectionUtils$MultiValueMapAdapter",
      "org.springframework.http.HttpEntity",
      "org.springframework.http.ResponseEntity",
      "org.springframework.http.ResponseEntity$DefaultBuilder",
      "org.springframework.util.LinkedCaseInsensitiveMap$EntrySet",
      "org.springframework.http.MediaType$1",
      "org.springframework.http.MediaType",
      "org.springframework.core.io.AbstractResource",
      "org.springframework.core.io.FileSystemResource",
      "org.springframework.util.LinkedCaseInsensitiveMap$EntryIterator",
      "org.springframework.util.LinkedCaseInsensitiveMap$EntrySetIterator",
      "org.springframework.util.ObjectUtils",
      "org.springframework.util.InvalidMimeTypeException",
      "org.springframework.http.InvalidMediaTypeException"
    );
  }
}
