dist: trusty
sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

branches:
  only:
    - master
env:
  global:
    - secure: "53wVXTm2nKnkEmyeW93BMyqhTmht6oBGRKdIEi/zMPoZPTp2c4MF42csaxTiLfX2A0LxTQtL7Y+chkA5J+YtpioFMUt+25h8d0jHdLautQXpuDcKZx/+74FkwylRKg4OrPbELYp1oDDN5ErqgFuiGHQmLeanB/kQMspdKvrF4uDCAXSseQLoRitkGMeA6nOaRZ9g5Ip3n4//dVD7tYT5wZIU6eGECOSLi3pGIW1kCcvrli9guZxr0yo/QGngnHoCPGZ+DeGrjABYrfIacmBEdW3Jt19wDUTZ1UPQZJqwcXt+zXaUkq135/xlgGwwsTc2F0/99YZ+ULRRhPPlA7aiACcDn1K0figyYEDSzuS8MFR8N0Uhohu/S/6e37264WbPwNRpCh8oWG1AMhaWd+AIH7n7tLNjN3PkGXn6dntJG/3ifnOjkQy5nQWGFDbXZA7Ru36ZfWvpeu9QRYp+quLgqsRtPtmx2WILqSAxz3gNetDicigRcG6gQ0wvuj2redSFnCx7EsXgIKrUWSx38mETt7AP2XVcDMcM9rLPYH9b7ickDm0MCCs3WlS6/OgT7kRDKaLmSSYLMCMp1toKzvUEIsR4qYZEXL5QzSBEAESA6kxbfNJCEZpMlCTbusLTN/vtbRQvMd09paKIScGels0spgcXoEgRi5NZbB+L7rJADy4="
    - secure: "5R/W3rGVTve0Y5VCJQ2YwHEyLeAmoHH9bw2ysWJ5l312kJ4U+Aanb45FEJiMBrJ47h+murZ9YCHI21nYcZbGJRSMRq8T/Pw3/eUObNiYiOvo2GHReD2DvMlGczuPYiuzoUSUuLcWWPybD7MIHhB+byDW2QdkAeD+cUzhPLJs/ep8gMcLAm45wyp/csn6MDSE8QQy64ekHhnh67i7xjAUK4F8rXF/ElCyAxIV/UKelnh5aUGht+5yRdYxhTYmhj3MtTB3s9F4JgrSxQ8v8AgR+OerupyuMjn/MpfKz9UnI0VM3lGrcKiWl5OSWfaESVhGZkFN6ZKuCanLLn47QDS+WX/pe9P1q7uvfeim3tMP1vIrixCDICs077ymkZ2F39OaqQ7dPDJY8tPHD2mblezMyfXWkwF1L6Ie4ES4lCnOlL59ar27ZOEpOvUkPzU+Ovs+MevWA6OVYNuOyOO6WE9/JKXe7lVOFTy7wFvx/vkLE1+5Y1yzI3hqN17JUafSQl8wmi1UdOSnTS7P/T3/msWnZ9YFFmTl5lZ/+EghkT+hHKLyZ6iloi/IUTwrK8EraDcV/+/siT9qeiLKIKRmuDwzp4On1oSROWud+zckQq44F9xIy8iDP4WK7fVRnp+QHxX1d2Vd5eY1iApQT56d78joTU8XvOV3C3ZsJkDjBLrL4Dg="
    - COMMIT=latest

script: "mvn cobertura:cobertura"

branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # REGISTRY
  - export REGISTRY=abingcbc/chisha-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=abingcbc/chisha-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # USER-SERVICE
  - export USER_SERVICE=abingcbc/chisha-user-service
  - docker build -t $USER_SERVICE:$COMMIT ./user-service
  - docker tag $USER_SERVICE:$COMMIT $USER_SERVICE:$TAG
  - docker push $USER_SERVICE

  # RECOMMEND-SERVICE
  - export RECOMMEND_SERVICE=abingcbc/chisha-recommend-service
  - docker build -t $RECOMMEND_SERVICE:$COMMIT ./recommend-service
  - docker tag $RECOMMEND_SERVICE:$COMMIT $RECOMMEND_SERVICE:$TAG
  - docker push $RECOMMEND_SERVICE
