version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: abingcbc/chisha-registry
    restart: always
    ports:
      - 8888:8888
    networks:
      - host
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: abingcbc/chisha-gateway
    restart: always
    ports:
      - 8070:8070
    networks:
      - host
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  user-service:
    image: abingcbc/chisha-user-service
    restart: always
    ports:
      - 8001:8001
    networks:
      - host
    logging:
      options:
        max-size: "10m"
        max-file: "10"
