/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 25 15:29:21 GMT 2019
 */

package org.sse.userservice.model;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.sse.userservice.model.User;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class User_ESTest extends User_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      User user0 = new User();
      user0.setUserId((-3593L));
      user0.hashCode();
      assertEquals((-3593L), user0.getUserId());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      User user0 = new User();
      user0.setUserId((-2455L));
      User user1 = new User();
      boolean boolean0 = user0.equals(user1);
      assertEquals((-2455L), user0.getUserId());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.equals(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      User user0 = new User();
      user0.setUserId((-1L));
      long long0 = user0.getUserId();
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      User user0 = new User();
      user0.setPhone("e)rh");
      String string0 = user0.getPhone();
      assertEquals("e)rh", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      User user0 = new User();
      user0.setPhone("");
      String string0 = user0.getPhone();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      User user0 = new User();
      user0.setPassword("e+1Mk@5dX{xydU");
      String string0 = user0.getPassword();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      User user0 = new User();
      user0.setPassword("");
      String string0 = user0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      User user0 = new User();
      user0.setNickname("org.sse.userservice.model.User");
      String string0 = user0.getNickname();
      assertEquals("org.sse.userservice.model.User", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      User user0 = new User();
      user0.setNickname("");
      String string0 = user0.getNickname();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      User user0 = new User();
      user0.setIsAuthorized("User(userId=0, nickname=null, phone=null, email=null, isAuthorized=null, gender=0, password=, isAuthorized=, bornPlace=, isAuthorized=, age=0)");
      String string0 = user0.getIsAuthorized();
      assertEquals("User(userId=0, nickname=null, phone=null, email=null, isAuthorized=null, gender=0, password=, isAuthorized=, bornPlace=, isAuthorized=, age=0)", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      User user0 = new User();
      user0.setIsAuthorized("");
      String string0 = user0.getIsAuthorized();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      User user0 = new User();
      user0.setGender(1157L);
      long long0 = user0.getGender();
      assertEquals(1157L, long0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      User user0 = new User();
      user0.setGender((-2678L));
      long long0 = user0.getGender();
      assertEquals((-2678L), long0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      User user0 = new User();
      user0.setEmail("xzlB]g@");
      String string0 = user0.getEmail();
      assertEquals("xzlB]g@", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      User user0 = new User();
      user0.setEmail("");
      String string0 = user0.getEmail();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      User user0 = new User();
      user0.setBornPlace("org.sse.userservice.model.User");
      String string0 = user0.getBornPlace();
      assertEquals("org.sse.userservice.model.User", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      User user0 = new User();
      user0.setBornPlace("");
      String string0 = user0.getBornPlace();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      User user0 = new User();
      user0.setAge(1L);
      long long0 = user0.getAge();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      User user0 = new User();
      user0.setAge((-3473L));
      long long0 = user0.getAge();
      assertEquals((-3473L), long0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.canEqual(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.canEqual((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      User user0 = new User();
      long long0 = user0.getGender();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getNickname();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getIsAuthorized();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      User user0 = new User();
      long long0 = user0.getAge();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      User user0 = new User();
      long long0 = user0.getUserId();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getBornPlace();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getPhone();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      user1.setAge((-258L));
      boolean boolean0 = user0.equals(user1);
      assertEquals((-258L), user1.getAge());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      User user0 = new User();
      user0.setBornPlace("");
      User user1 = new User();
      assertFalse(user1.equals((Object)user0));
      
      user1.setBornPlace("");
      boolean boolean0 = user0.equals(user1);
      assertTrue(user1.equals((Object)user0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      assertTrue(user1.equals((Object)user0));
      
      user1.setBornPlace("");
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      User user0 = new User();
      user0.setPhone("");
      user0.setBornPlace("");
      User user1 = new User();
      user1.setPhone("");
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      user1.setPassword("");
      assertFalse(user1.equals((Object)user0));
      
      user0.setPassword("");
      boolean boolean0 = user0.equals(user1);
      assertTrue(user1.equals((Object)user0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      assertTrue(user1.equals((Object)user0));
      
      user1.setPassword("");
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      assertTrue(user1.equals((Object)user0));
      
      user0.setPassword("");
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      user0.setGender(2083L);
      boolean boolean0 = user1.equals(user0);
      assertEquals(2083L, user0.getGender());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      user0.setIsAuthorized("eK]=QjLl");
      assertFalse(user0.equals((Object)user1));
      
      user1.setIsAuthorized("eK]=QjLl");
      boolean boolean0 = user0.equals(user1);
      assertTrue(user1.equals((Object)user0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      assertTrue(user1.equals((Object)user0));
      
      user1.setIsAuthorized(",");
      boolean boolean0 = user0.equals(user1);
      assertFalse(user1.equals((Object)user0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      User user0 = new User();
      user0.setIsAuthorized("");
      user0.setPhone("");
      user0.setEmail("");
      User user1 = new User();
      user1.setEmail("");
      user1.setPhone("");
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      User user0 = new User();
      user0.setPhone("hZ7'`1mY}\u0000");
      User user1 = new User();
      user1.setPhone("hZ7'`1mY}\u0000");
      assertTrue(user1.equals((Object)user0));
      
      user1.setEmail("hZ7'`1mY}\u0000");
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      User user0 = new User();
      user0.setPhone("");
      user0.setEmail("");
      User user1 = new User();
      user1.setPhone("");
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      assertTrue(user1.equals((Object)user0));
      
      user1.setPhone(",^ gende=");
      boolean boolean0 = user0.equals(user1);
      assertFalse(user1.equals((Object)user0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      User user0 = new User();
      user0.setPhone("");
      User user1 = new User();
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      User user0 = new User();
      user0.setNickname("");
      User user1 = new User();
      assertFalse(user1.equals((Object)user0));
      
      user1.setNickname("");
      boolean boolean0 = user0.equals(user1);
      assertTrue(user1.equals((Object)user0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      User user0 = new User();
      User user1 = new User();
      assertTrue(user1.equals((Object)user0));
      
      user1.setNickname("<H8~=3t7n/");
      boolean boolean0 = user0.equals(user1);
      assertFalse(user1.equals((Object)user0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      User user0 = new User();
      user0.setNickname("User(userId=0, nickname=null, phone=null, email=null, isAuthorized=null, gender=0, password=null, bornPlace=null, age=0)");
      User user1 = new User();
      boolean boolean0 = user0.equals(user1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      User user0 = new User();
      user0.setUserId(4171L);
      User user1 = new User();
      boolean boolean0 = user0.equals(user1);
      assertEquals(4171L, user0.getUserId());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.equals("User(userId=0, nickname=null, phone=null, email=~;JWg-}u+|nQn}S, isAuthorized=4>e*r9kxv<]dck0, gender=0, password=, bornPlace=, age=-1)");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      User user0 = new User();
      user0.setEmail("~;JWg-}u+|nQn}S");
      user0.hashCode();
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      User user0 = new User();
      user0.setNickname(", email=");
      user0.hashCode();
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      User user0 = new User();
      user0.setIsAuthorized("4>e*r9kxv<]dck0");
      user0.hashCode();
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      User user0 = new User();
      user0.setPassword("");
      user0.hashCode();
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.toString();
      assertEquals("User(userId=0, nickname=null, phone=null, email=null, isAuthorized=null, gender=0, password=null, bornPlace=null, age=0)", string0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      User user0 = new User();
      user0.setBornPlace("");
      user0.hashCode();
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      User user0 = new User();
      user0.setUserId(1L);
      long long0 = user0.getUserId();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      User user0 = new User();
      user0.setPhone("");
      user0.hashCode();
  }
}
