/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 26 02:56:18 GMT 2019
 */

package org.sse.userservice.config;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.sse.userservice.config.SwaggerConfig;
import springfox.documentation.spring.web.plugins.Docket;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SwaggerConfig_ESTest extends SwaggerConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SwaggerConfig swaggerConfig0 = new SwaggerConfig();
      Docket docket0 = swaggerConfig0.api();
      assertEquals("user-service", docket0.getGroupName());
  }
}
