/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Dec 26 02:56:18 GMT 2019
 */

package org.sse.userservice.config;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class SwaggerConfig_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.sse.userservice.config.SwaggerConfig"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/d3/k2gc1l3d2v56t6f1l9xsh6jm0000gn/T/"); 
    java.lang.System.setProperty("user.country", "CN"); 
    java.lang.System.setProperty("user.dir", "/Users/cbc/Project/Java/ChiSha/user-service"); 
    java.lang.System.setProperty("user.home", "/Users/cbc"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "cbc"); 
    java.lang.System.setProperty("user.timezone", "Asia/Shanghai"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SwaggerConfig_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.plugin.metadata.SimplePluginMetadata",
      "com.google.common.base.Joiner$1",
      "com.google.common.base.Joiner$2",
      "springfox.documentation.spi.schema.GenericTypeNamingStrategy",
      "com.google.common.collect.Lists$RandomAccessPartition",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableEnumMap",
      "springfox.documentation.service.Contact",
      "springfox.documentation.builders.RequestHandlerSelectors",
      "com.google.common.collect.Collections2",
      "com.fasterxml.classmate.ResolvedType",
      "springfox.documentation.builders.BuilderDefaults",
      "springfox.documentation.spi.service.DocumentationPlugin",
      "com.google.common.collect.Lists$RandomAccessListWrapper",
      "com.google.common.collect.ImmutableEnumSet",
      "org.springframework.util.MimeType",
      "com.google.common.base.Predicates$ObjectPredicate",
      "com.google.common.base.Optional",
      "com.google.common.collect.Lists$TransformingRandomAccessList",
      "com.google.common.collect.Sets$2",
      "com.google.common.collect.Sets$3",
      "com.google.common.collect.Sets$1",
      "com.google.common.base.Predicates$AndPredicate",
      "com.google.common.collect.BiMap",
      "com.google.common.base.Function",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.collect.Lists$AbstractListWrapper",
      "com.google.common.collect.ImmutableMap",
      "org.springframework.http.MediaType",
      "springfox.documentation.builders.PathSelectors",
      "com.google.common.collect.Maps$1",
      "org.springframework.web.bind.annotation.RequestMethod",
      "com.google.common.base.Predicates$NotPredicate",
      "com.google.common.collect.SortedMapDifference",
      "com.google.common.collect.Sets",
      "springfox.documentation.annotations.ApiIgnore",
      "org.springframework.context.annotation.Configuration",
      "org.springframework.plugin.metadata.PluginMetadata",
      "com.google.common.base.Predicate",
      "org.springframework.util.CollectionUtils",
      "com.google.common.collect.Lists$StringAsImmutableList",
      "springfox.documentation.spi.service.contexts.DocumentationContextBuilder",
      "com.google.common.collect.Lists$2",
      "springfox.documentation.schema.AlternateTypeRule",
      "com.google.common.base.Present",
      "springfox.documentation.spi.service.contexts.ApiSelector",
      "com.google.common.collect.Lists$1",
      "com.google.common.base.Joiner",
      "org.springframework.core.Ordered",
      "com.google.common.collect.Multiset",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "com.google.common.collect.Sets$SetView",
      "org.springframework.http.MediaType$1",
      "com.google.common.base.Predicates$ObjectPredicate$1",
      "com.google.common.collect.Multimap",
      "org.sse.userservice.config.SwaggerConfig",
      "com.google.common.collect.Lists$Partition",
      "springfox.documentation.service.ApiInfo",
      "com.google.common.collect.Lists",
      "springfox.documentation.spring.web.plugins.ApiSelectorBuilder$1",
      "com.google.common.collect.ImmutableList",
      "springfox.documentation.builders.RequestHandlerSelectors$2",
      "springfox.documentation.spring.web.plugins.ApiSelectorBuilder",
      "springfox.documentation.service.Tag",
      "springfox.documentation.swagger2.annotations.EnableSwagger2",
      "org.springframework.util.MimeType$SpecificityComparator",
      "com.google.common.base.Predicates",
      "springfox.documentation.builders.RequestHandlerSelectors$1",
      "com.google.common.collect.Lists$TransformingSequentialList",
      "org.springframework.util.InvalidMimeTypeException",
      "com.google.common.base.Absent",
      "org.springframework.context.annotation.Import",
      "org.springframework.util.MultiValueMap",
      "com.google.common.base.Joiner$MapJoiner",
      "springfox.documentation.spi.service.contexts.DocumentationContext",
      "com.google.common.collect.Maps",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.http.InvalidMediaTypeException",
      "com.google.common.collect.MapDifference",
      "org.springframework.stereotype.Component",
      "springfox.documentation.spi.DocumentationType",
      "com.google.common.collect.Maps$EntryTransformer",
      "org.springframework.plugin.core.Plugin",
      "com.google.common.collect.Ordering",
      "com.google.common.base.Predicates$ObjectPredicate$4",
      "springfox.documentation.spring.web.plugins.Docket",
      "com.google.common.base.Predicates$ObjectPredicate$3",
      "com.google.common.base.Predicates$ObjectPredicate$2",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.UnmodifiableIterator",
      "springfox.documentation.schema.DefaultGenericTypeNamingStrategy",
      "springfox.documentation.PathProvider",
      "org.springframework.util.Assert",
      "org.springframework.util.StringUtils"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SwaggerConfig_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.sse.userservice.config.SwaggerConfig",
      "org.springframework.beans.factory.annotation.Autowire",
      "org.springframework.plugin.metadata.SimplePluginMetadata",
      "org.springframework.util.MimeType",
      "org.springframework.util.Assert",
      "org.springframework.util.StringUtils",
      "org.springframework.util.CollectionUtils",
      "org.springframework.util.LinkedCaseInsensitiveMap",
      "org.springframework.util.LinkedCaseInsensitiveMap$1",
      "org.springframework.util.MimeType$SpecificityComparator",
      "org.springframework.http.MediaType$1",
      "org.springframework.http.MediaType",
      "springfox.documentation.spi.DocumentationType",
      "com.google.common.base.Predicates$ObjectPredicate",
      "springfox.documentation.spring.web.plugins.Docket",
      "com.google.common.collect.Lists",
      "com.google.common.base.Joiner",
      "com.google.common.base.Preconditions",
      "com.google.common.base.Joiner$1",
      "com.google.common.collect.Collections2",
      "com.google.common.base.Joiner$MapJoiner",
      "com.google.common.collect.Maps",
      "com.google.common.collect.Sets",
      "springfox.documentation.service.Contact",
      "springfox.documentation.service.ApiInfo",
      "springfox.documentation.schema.DefaultGenericTypeNamingStrategy",
      "com.google.common.base.Optional",
      "com.google.common.base.Absent",
      "springfox.documentation.builders.RequestHandlerSelectors",
      "springfox.documentation.builders.RequestHandlerSelectors$2",
      "com.google.common.base.Predicates",
      "com.google.common.base.Predicates$NotPredicate",
      "springfox.documentation.builders.RequestHandlerSelectors$1",
      "com.google.common.base.Predicates$AndPredicate",
      "springfox.documentation.builders.PathSelectors",
      "springfox.documentation.spi.service.contexts.ApiSelector",
      "springfox.documentation.spring.web.plugins.ApiSelectorBuilder",
      "springfox.documentation.spring.web.plugins.ApiSelectorBuilder$1",
      "springfox.documentation.builders.BuilderDefaults",
      "com.google.common.base.Present"
    );
  }
}
